### ISSUE TITLE
Add debug option 

### ISSUE THREAD

**Issue by todd-james** [hamishgibbs/lachesis#14]
- print out id of current visit being detected 
- and number of points in visit 
- index of last point

**Comment by hamishgibbs** [comment]
I think that the option to see "under the hood" at the points that are actually defining a visit is not a helpful addition to the API (usually there are too many points for it to make much sense). 

In the event of a bug, we should just isolate the root cause and use a debugger in development instead of giving the option to expose the visit detection internals to a user.
